#!/usr/bin/env bash

get-latest-tag(){
    LATEST_TAG=$(git describe --tags $(git rev-list --tags --max-count=1))
    echo "${LATEST_TAG}"
}


get-version-bump(){
    echo "$(get-version-bump)"
}

git fetch
git checkout main
echo "Latest tag: $(get-latest-tag)"
VERSION_BUMP=$(get-version-bump)
echo "Version bump: $VERSION_BUMP"
git tag $VERSION_BUMP
git push origin $VERSION_BUMP




